#!/bin/bash

# A script to check for commits that are added by a merge if their
# corresponding libsc commit is present in the libsc/prev3-develop.
# This script requires two command line parameters.
#
# ./build-aux/check_sc BASE_BRANCH BRANCH_TO_MERGE
#
# Both passed branches must be branches in p4est.
#
# This script checks the ancestor relation for each new p4est commit that
# would be added to the BASE_BRANCH in case of a merge. This means that
# for multiple p4est commits the same libsc commit may be checked since
# the libsc commits may coincide for multiple p4est commits.
# This script must be executed in the source directory of p4est.

count=0

if test $# -ne 2; then
  echo >&2 "Usage: ./build-aux/check_sc BASE_BRANCH BRANCH_TO_MERGE"
  exit 2
fi

for commit in $(git rev-list $1..$2)
#for commit in $(git rev-list prev3-develop)
do
  # loop over all commits that feature-mpi-write is ahead of prev3-develop
  # get the corresponding libsc commit
  sc=$(git ls-tree $commit | grep sc | cut -d' ' -f3)
  # extract hash value
  sc_commit=$(echo $sc | cut -d' ' -f1)
  cd sc
  # check ancestor relation (grep with 'not' to see only negativ results)
  if git merge-base --is-ancestor $sc_commit prev3-develop; then
    echo "$sc_commit is an ancestor of libsc/prev3-develop"
  else
    echo "$sc_commit is not an ancestor of libsc/prev3-develop"
  fi
  cd ..
  ((count++))
done

echo "Checked" $count "p4est commits"
