name: CI for CMake

on:
  push:
    paths:
      - sc
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.cmake.in"
      - "**.c"
      - "**.h"
      - "**.h.in"
      - ".github/workflows/ci_cmake.yml"
  pull_request:
  release:
    types: [published]

env:
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_NO_TESTS_ACTION: "error"
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs

jobs:

  linux-gcc14:
    runs-on: ubuntu-24.04
    name: Linux mpi=${{ matrix.mpi }} CC=${{ matrix.cc }} shared=${{ matrix.shared }}
    timeout-minutes: 61

    strategy:
      matrix:
        cc: [gcc-12, gcc-13, gcc-14]
        shared: [false]
        mpi: [mpich]
        include:
        - cc: gcc
          shared: true
          mpi: mpich
        - cc: gcc
          shared: false
          mpi: openmpi


    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends zlib1g-dev lib${{ matrix.mpi }}-dev

    - name: CMake build-test-install-package
      uses: ./.github/workflows/composite-unix

    - name: Upload package
      uses: ./.github/workflows/composite-pkg


  linux-gcc9:
    runs-on: ubuntu-22.04
    name: Linux mpi=${{ matrix.mpi }} CC=${{ matrix.cc }} shared=${{ matrix.shared }}
    timeout-minutes: 60

    strategy:
      matrix:
        cc: [gcc-9, gcc-10, gcc-11]
        shared: [false]
        mpi: [mpich]

    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends zlib1g-dev lib${{ matrix.mpi }}-dev

    - name: CMake build-test-install-package
      uses: ./.github/workflows/composite-unix

    - name: Upload package
      uses: ./.github/workflows/composite-pkg


  mac:
    runs-on: macos-14
    name: macOS CC=${{ matrix.cc }} shared=${{ matrix.shared }}
    timeout-minutes: 60

    strategy:
      matrix:
        cc: [clang, gcc-13]
        shared: [false]
        include:
        - cc: clang
          shared: true

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Install system dependencies
      run: brew install open-mpi

    - name: CMake build-test-install-package
      uses: ./.github/workflows/composite-unix

    - name: Upload package
      uses: ./.github/workflows/composite-pkg


  windows:
    runs-on: windows-latest
    name: Windows
    timeout-minutes: 60

    strategy:
      matrix:
        shared: [false]

    env:
      CMAKE_GENERATOR: "MinGW Makefiles"
      CMAKE_INSTALL_PREFIX: libs
      CMAKE_PREFIX_PATH: libs

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-zlib

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4
      name: Checkout source code

    # Windows MPI is shaky in general on GitHub Actions, so we don't use it
    - name: CMake configure without MPI
      run: >-
        cmake --preset default
        -Dmpi:BOOL=no
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
      env:
        ZLIB_ROOT: ${{ runner.temp }}/msys64/mingw64

    - name: CMake build
      run: cmake --build --preset default

    - name: CMake self-tests
      run: ctest --preset default

    - name: install p4est CMake package
      run: cmake --install build

    - name: CMake configure examples
      run: >-
        cmake -B example/build -S example
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
        -DZLIB_ROOT:PATH=${{ runner.temp }}/msys64/mingw64/

    - name: CMake build examples
      run: cmake --build example/build

    - name: Create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload package
      uses: ./.github/workflows/composite-pkg
